/**
 * Frontend domain types now come from the shared contract (single source of truth
 * for both sides). This file re-exports them so existing `@/lib/types` imports keep
 * working; change a shape in `shared/contract.ts` and it type-errors here AND in the
 * backend serializers that are typed against the same contract.
 */
export type {
  Role,
  StoreStatus,
  OrderStatus,
  DiscountType,
  ShippingType,
  AnalyticsEventType,
  StoreReviewStatus,
  OwnerStatus,
  TicketStatus,
  TicketPriority,
  FlagStatus,
  FlagSeverity,
  TicketAuthor,
  ShopRequestStatus,
  ShopRequestPlan,
  StorePlan,
  PlanStatus,
  PaymentMethod,
  StorefrontTemplate,
  ThemeOverrides,
  ProductDetails,
  ProductAttributeValue,
  ProductSellingType,
  ProductCatalogStatus,
  ProductImageAsset,
  ProductOptionValue,
  ProductOption,
  ProductVariant,
  ProductDetailRow,
  User,
  Store,
  Product,
  Discount,
  OrderItem,
  Order,
  AnalyticsEvent,
  PlatformSettings,
  TicketMessage,
  SupportTicket,
  ProductFlag,
  ShopRequest,
  AuditLog,
} from '@shared/contract';
